### ISSUE TITLE
Some Placeholders can not work.

### ISSUE THREAD

**Issue by zsn741656478** [happyzleaf/PixelmonPlaceholders#23]
Like this: 
%trainer_team_1_evolutiontype%
%trainer_team_1_evolution_level_specificlevel%
%trainer_team_1_evolution_bystone_stone%
etc...
All Placeholder related to evolve also can't work.

**Comment by hqppyz** [comment]
Yeah so I'm not totally sure how that happened, but the wiki is totally wrong there.
You must specify which evolution you're talking about, so in most cases you can just do %party_1_evolution_1_level%.
See how I used %party_1 instead of %trainer_team_1, it's the new alternative
I'll try to see if I can get the wiki updated. but I doubt it's gonna happen too soon.

**Comment by zsn741656478** [comment]
Ok. I understand.

**Comment by hqppyz** [comment]
I'm closing this for now, feel free to reopen it to ask further questions regarding the evolutions.
