### ISSUE TITLE
Not support pixelmon generation

### ISSUE THREAD

**Issue by comdarksider** [happyzleaf/PixelmonPlaceholders#33]
Please make plugin for pixelmon generation 2.9.1

**Comment by hqppyz** [comment]
Nope, none of my plugins will ever explicitly support Generations.
I'd also have to make **major** changes because the gens code simply isn't as updated as Reforged, and a **lot** of stuff would need to be fixed.
The code is public and open, if anyone is willing to fork this repo and downgrade it to gens, they're more than free to do so.
