### ISSUE TITLE
Suggestion of new placeholder - Moves

### ISSUE THREAD

**Issue by Lorrainrm** [happyzleaf/PixelmonPlaceholders#7]
Perhaps a _allmoves% / _allmoves_1% / 2, 3, 4...

%trainer_team_1_allmoves% would print all moves learnable by the pokemon in slot 1
%trainer_team_1_allmoves_1% would print the first in the list
2 would brind the second, etc etc..

Would be usefull for a custom menu where a player could pick the moves to learn, for example. Like a custom move relearner menu.

**Comment by hqppyz** [comment]
These placeholders have been around since the first release probably, next time you might want to go and take a look at the [wiki](https://github.com/happyzleaf/PixelmonPlaceholders/wiki/Placeholders) ;)
![image](https://user-images.githubusercontent.com/17068881/37869747-b00ac0e4-2fbd-11e8-8bbd-45c23ca5304a.png)

**Comment by Lorrainrm** [comment]
Ye, it shows the moveset from the poke, not the LEARNABLE moves, like /moves <pokemon> . Sorry i meant this, but my post was confusing.

**Comment by hqppyz** [comment]
Alright, gotta go and see what i can do :P 
By the way, sorry, your post was not confusing, i just can't read :/

**Comment by hqppyz** [comment]
@Lorrainrm alright, added what you've asked for.
Sorry if i didn't understand your first message, it was all on me, i've completely missed the "learnable" part for some reasons lol.
Closing :)
